export const supabaseUrl = 'https://ornhrekzrrwexxuekbjt.supabase.co';
export const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ybmhyZWt6cnJ3ZXh4dWVrYmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTY0ODAzNDUsImV4cCI6MjAzMjA1NjM0NX0.928c7xqMEcAGwrHstkutRFIzSQX0OBmneXrCSjYRt9Y';
